apiVersion: 1

datasources:
  - name: PostgreSQL
    uid: postgres_ai_monitoring
    type: postgres
    access: proxy
    url: postgres:5432
    database: ai_monitoring
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      maxOpenConns: 100
      maxIdleConns: 100
      connMaxLifetime: 14400
      connMaxIdleTime: 14400
    isDefault: true

  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
